export const QUOTES: Record<string, string[]> = {
    admin: [
        "Leadership is the capacity to translate vision into reality. — Warren Bennis",
        "Management is doing things right; leadership is doing the right things. — Peter Drucker",
        "The greatest leader is the one that gets the people to do the greatest things. — Ronald Reagan",
        "A leader is one who knows the way, goes the way, and shows the way. — John Maxwell",
        "Innovation distinguishes between a leader and a follower. — Steve Jobs",
        "Leadership is not about being in charge. It is about taking care of those in your charge. — Simon Sinek",
        "The art of leadership is saying no, not saying yes. — Tony Blair",
        "A person who never made a mistake never tried anything new. — Albert Einstein",
        "Great leaders don't set out to be a leader; they set out to make a difference. ",
        "The best way to predict the future is to create it. — Peter Drucker",
        "Leadership is an action, not a position. — Donald McGannon",
        "To handle yourself, use your head; to handle others, use your heart. — Eleanor Roosevelt",
        "Vision without action is a daydream. Action without vision is a nightmare. — Japanese Proverb",
        "Example is not the main thing in influencing others. It is the only thing. — Albert Schweitzer",
        "Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others. — Jack Welch",
        "Leadership is the art of giving people a platform for spreading ideas that work. — Seth Godin",
        "Focus on the solution, not the problem. ",
        "The most dangerous leadership myth is that leaders are born. — Warren Bennis",
        "A leader is a dealer in hope. — Napoleon Bonaparte",
        "Excellence is not a skill. It is an attitude. — Ralph Marston",
        "Integrity is the most valuable and respected quality of leadership. Always keep your word. — Brian Tracy",
        "Effective leadership is not about making speeches or being liked; leadership is defined by results not attributes. — Peter Drucker",
        "The growth and development of people is the highest calling of leadership. — Harvey Firestone",
        "A true leader has the confidence to stand alone, the courage to make tough decisions, and the compassion to listen to the needs of others. — Douglas MacArthur",
        "The key to successful leadership today is influence, not authority. — Kenneth Blanchard",
        "Leaders must be close enough to relate to others, but far enough ahead to motivate them. — John C. Maxwell",
        "It is better to lead from behind and to put others in front, especially when you celebrate victory when nice things occur. — Nelson Mandela",
        "If your actions inspire others to dream more, learn more, do more and become more, you are a leader. — John Quincy Adams",
        "The function of leadership is to produce more leaders, not more followers. — Ralph Nader",
        "Average leaders raise the bar on themselves; good leaders raise the bar for others; great leaders inspire others to raise their own bar. — Orrin Woodward"
    ],
    controller: [
        "Efficiency is doing things right; effectiveness is doing the right things. — Peter Drucker",
        "Control your workflow, or your workflow will control you. ",
        "The first rule of any technology used in a business is that automation applied to an efficient operation will magnify the efficiency. — Bill Gates",
        "Discipline is the bridge between goals and accomplishment. — Jim Rohn",
        "Process and strategy are the engines of execution. ",
        "Simplicity is the soul of efficiency. — Austin Freeman",
        "Quality is not an act, it is a habit. — Aristotle",
        "The way to get started is to quit talking and begin doing. — Walt Disney",
        "Focus on being productive instead of busy. — Tim Ferriss",
        "Productivity is never an accident. It is always the result of a commitment to excellence, intelligent planning, and focused effort. — Paul J. Meyer",
        "The goal is not to do more; it is to have less to do. ",
        "Order is the foundation of all things. — Edmund Burke",
        "Good management is the art of making problems so interesting and their solutions so constructive that everyone wants to get to work and deal with them. — Paul Hawken",
        "Continuous improvement is better than delayed perfection. — Mark Twain",
        "The essence of strategy is choosing what not to do. — Michael Porter",
        "Measure what is measurable, and make measurable what is not so. — Galileo Galilei",
        "Action is the foundational key to all success. — Pablo Picasso",
        "A goal without a plan is just a wish. — Antoine de Saint-Exupéry",
        "Plan your work and work your plan. — Napoleon Hill",
        "By failing to prepare, you are preparing to fail. — Benjamin Franklin",
        "You can't manage what you don't measure. — Peter Drucker",
        "The efficiency of a system is proportional to the flow of information. ",
        "Details matter, it's worth waiting to get it right. — Steve Jobs",
        "Perfection is not attainable, but if we chase perfection we can catch excellence. — Vince Lombardi",
        "It's not about the goal. It's about becoming the person that can accomplish the goal. — Tony Robbins",
        "Concentrate all your thoughts upon the work at hand. The sun's rays do not burn until brought to a focus. — Alexander Graham Bell",
        "Your work is going to fill a large part of your life, and the only way to be truly satisfied is to do what you believe is great work. — Steve Jobs",
        "The secret of getting ahead is getting started. — Mark Twain",
        "Believe you can and you're halfway there. — Theodore Roosevelt",
        "The only way to do great work is to love what you do. — Steve Jobs"
    ],
    member: [
        "Hard work beats talent when talent doesn't work hard. — Tim Notke",
        "Success is the sum of small efforts, repeated day-in and day-out. — Robert Collier",
        "The only way to do great work is to love what you do. — Steve Jobs",
        "Believe you can and you're halfway there. — Theodore Roosevelt",
        "Success is not final, failure is not fatal: it is the courage to continue that counts. — Winston Churchill",
        "Don't watch the clock; do what it does. Keep going. — Sam Levenson",
        "Opportunities are usually disguised as hard work, so most people don't recognize them. — Ann Landers",
        "The road to success and the road to failure are almost exactly the same. — Colin R. Davis",
        "Your talent determines what you can do. Your motivation determines how much you are willing to do. Your attitude determines how well you do it. — Lou Holtz",
        "Execution is everything. — Jeff Bezos",
        "Start where you are. Use what you have. Do what you can. — Arthur Ashe",
        "There are no shortcuts to any place worth going. — Beverly Sills",
        "Professionalism is not the job you do; it's how you do the job. ",
        "The future depends on what you do today. — Mahatma Gandhi",
        "Consistency is what transforms average into excellence. ",
        "Do what you can, with what you have, where you are. — Theodore Roosevelt",
        "Hard work spotlights the character of people. — Joe Namath",
        "The difference between ordinary and extraordinary is that little extra. — Jimmy Johnson",
        "Setting goals is the first step in turning the invisible into the visible. — Tony Robbins",
        "Strive not to be a success, but rather to be of value. — Albert Einstein",
        "You don't have to be great to start, but you have to start to be great. — Zig Ziglar",
        "Work hard in silence, let your success be your noise. — Frank Ocean",
        "Nothing worth having comes easy. — Theodore Roosevelt",
        "Persistence is the twin sister of excellence. One is a matter of quality; the other, a matter of time. — Marabel Morgan",
        "Genius is 1% inspiration and 99% perspiration. — Thomas Edison",
        "Focus on the journey, not the destination. — Greg Anderson",
        "The only limit to our realization of tomorrow will be our doubts of today. — Franklin D. Roosevelt",
        "If you want to live a happy life, tie it to a goal, not to people or things. — Albert Einstein",
        "I find that the harder I work, the more luck I seem to have. — Thomas Jefferson",
        "Dream big and dare to fail. — Norman Vaughan"
    ],
    default: [
        "Success is a journey, not a destination. — Ben Sweetland",
        "Every accomplish starts with the decision to try. ",
        "Do something today that your future self will thank you for. ",
        "Believe in yourself and all that you are. — Christian D. Larson",
        "The only person you should try to be better than is the person you were yesterday. — Matty Mullins",
        "Courage is not the absence of fear, but the triumph over it. — Nelson Mandela",
        "It always seems impossible until it's done. — Nelson Mandela",
        "Believe you can and you're halfway there. — Theodore Roosevelt",
        "Don't stop until you're proud. ",
        "Keep going, you're doing great! "
    ]
};
